version: '0.2.3.{build}'
image:
  - Visual Studio 2015
  - Visual Studio 2017
configuration:
  - Release
environment:
  matrix:
    - arch: Win64
    - arch: Win32
matrix:
  fast_finish: true
before_build:
  - ps: .\scripts\configure-cmake.ps1
build:
  project: build\vc\cgss.sln
  verbosity: minimal
  parallel: true
after_build:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - ps: .\scripts\package-artifacts.ps1
test: off
artifacts:
  - path: 'libcgss-*.zip'
    name: 'Binaries'
