version: '0.3.7.{build}'
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CONFIGURATION: Release
      ARCH: Win64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CONFIGURATION: Release
      ARCH: Win32
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CONFIGURATION: Release
      ARCH: Win64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CONFIGURATION: Release
      ARCH: Win32
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CONFIGURATION: Release
      ARCH: Win64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CONFIGURATION: Release
      ARCH: Win32
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
  CGSS_BUILD_JNI_LIBRARY: ON
matrix:
  fast_finish: true
for:
  - matrix:
      except:
        - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    environment:
      JAVA_HOME: C:\Program Files\Java\jdk1.8.0
install:
  - pwsh: ./scripts/install.ps1
before_build:
  - pwsh: ./scripts/configure-cmake.ps1
build_script:
  - pwsh: ./scripts/build-project.ps1
after_build:
  - pwsh: ./scripts/package-artifacts.ps1
test: false
deploy:
  - provider: GitHub
    description: 'libcgss'
    auth_token:
      secure: u+MFjjY665AT4PHJ2bFMINBLnnnwSj1jLnNeFZoWfeYbomTNSPOmdahffmZa+dRH
    artifact: 'Binaries'             # upload all NuGet packages to release assets
    draft: false
    prerelease: false
    on:
      APPVEYOR_REPO_TAG: true        # deploy on tag push only
