version: '0.3.4.{build}'
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CONFIGURATION: Release
      ARCH: Win64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CONFIGURATION: Release
      ARCH: Win32
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CONFIGURATION: Release
      ARCH: Win64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CONFIGURATION: Release
      ARCH: Win32
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CONFIGURATION: Release
      ARCH: Win64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CONFIGURATION: Release
      ARCH: Win32
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
matrix:
  fast_finish: true
before_build:
  - pwsh: ./scripts/configure-cmake.ps1
build_script:
  - pwsh: ./scripts/build-project.ps1
after_build:
  - pwsh: ./scripts/package-artifacts.ps1
test: false
deploy:
  - provider: GitHub
    description: 'libcgss'
    auth_token:
      secure: u+MFjjY665AT4PHJ2bFMINBLnnnwSj1jLnNeFZoWfeYbomTNSPOmdahffmZa+dRH
    artifact: 'Binaries'             # upload all NuGet packages to release assets
    draft: false
    prerelease: false
    on:
      APPVEYOR_REPO_TAG: true        # deploy on tag push only
