version: '0.3.0.{build}'
image:
  - Visual Studio 2015
  - Visual Studio 2017
configuration:
  - Release
environment:
  matrix:
    - arch: Win64
    - arch: Win32
matrix:
  fast_finish: true
before_build:
  - ps: .\scripts\configure-cmake.ps1
build:
  project: build\vc\cgss.sln
  verbosity: minimal
  parallel: true
after_build:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - ps: .\scripts\package-artifacts.ps1
test: off
artifacts:
  - path: 'libcgss-bin-*.zip'
    name: 'Binaries'
  - path: 'libcgss-ci-*.zip'
    name: 'CI auto update'
deploy:
  - provider: GitHub
    description: 'libcgss'
    auth_token:
      secure: u+MFjjY665AT4PHJ2bFMINBLnnnwSj1jLnNeFZoWfeYbomTNSPOmdahffmZa+dRH
    artifact: 'Binaries'             # upload all NuGet packages to release assets
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true        # deploy on tag push only
